services:
    # Сервис для PHP с FPM
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-php
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=blog_base
            - PHP_DATE_TIMEZONE=Asia/Almaty
            - SANCTUM_STATEFUL_DOMAINS=localhost,frontend-app.local

    # Сервис для Nginx
    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
            - ./storage:/var/www/storage
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - php

    # Сервис для MySQL
    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog_base
#            MYSQL_USER: root
#            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    # Сервис для phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql         # Указываем хост для подключения к MySQL (это имя сервиса MySQL)
            PMA_USER: root           # Имя пользователя MySQL
            PMA_PASSWORD: root       # Пароль пользователя MySQL
        ports:
            - "8080:80"              # Доступ к phpMyAdmin через порт 8080
        networks:
            - app-network
        depends_on:
            - mysql

    # Сервис для Composer (для удобства работы с зависимостями)
    composer:
        image: composer:latest
        container_name: laravel-composer
        volumes:
            - .:/app
        working_dir: /app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
